Feat/OH-102
One-Hunnit/OneHunnit-FE pull request #11
Opened 2024-10-02 08:11 UTC by rhdmswls12

## 관련 이슈

https://onehunnit.atlassian.net/browse/OH-102

## 작업 내용
- 기존에 있던 탭 라우팅 임시 설정
- RecoilRoot 추가
## 참고사항

2024-10-02 08:52 UTC, sjsjsj1246 reviewed
코멘트 남깃 것 작업 부탁드립니다.

2024-10-02 08:52 UTC, sjsjsj1246 commented on src/app/home/Home.tsx
> +import { Text, View } from 'react-native';
이 파일은 어디서 쓰이고있는건가요?

2024-10-02 08:52 UTC, sjsjsj1246 commented on src/app/(tabs)/_layout.tsx
>  export default function TabLayout() {
여기서부터 인증된 사용자 라우팅할 수 있도록 밑작업 해두는게 좋을 것 같네요 authStore도 있으니까요.

다음 가이드 따라서 작업해주세요. 로그인 기능은 없으니 일단은 인증 되었다고 가정하고 라우팅 해주세요.
[Using React Context and Route Groups](https://docs.expo.dev/router/reference/authentication/#using-react-context-and-route-groups)

2024-10-02 14:02 UTC, rhdmswls12 commented on src/app/home/Home.tsx
> +import { Text, View } from 'react-native';
/home 경로로 이동할 때 보이는 화면인데 생각해보니 루트 경로에서 보이는게 맞는 것 같아서 구조를 수정했습니다!

2024-10-02 15:06 UTC, rhdmswls12 commented on src/app/(tabs)/_layout.tsx
>  export default function TabLayout() {
넵 알겠습니다

2024-10-03 08:58 UTC, sjsjsj1246 requested changes

2024-10-03 08:58 UTC, sjsjsj1246 commented on src/app/(tabs)/_layout.tsx
> +  }
가이드 그대로 contextAPI를 쓰셨군요~ 그런데 저희는 recoil을 쓰고있고 또 authStore도 있는 상황이죠. 따라서 authStore에 있는 상태로 충분히 여기서 분기처리 해줄 수 있습니다.
그럼 ctx.tsx 파일도 필요 없어지죠. 이렇게 작업 부탁드립니다.

2024-10-03 09:04 UTC, rhdmswls12 commented on src/app/(tabs)/_layout.tsx
> +  }
넵 수정하겠습니다~

2024-10-03 16:42 UTC, sjsjsj1246 commented on src/stores/authStore.tsx
> +  storage: localStorage,
혹시 이거 잘 작동하시나요? 저는 잘 안띄워지는데요. react-native 환경에서 localstorage가 있나요?

2024-10-03 16:45 UTC, sjsjsj1246 commented on src/stores/authStore.tsx
> +  storage: localStorage,
보통 persist storage로 async storage를 쓰는 것 같네요
https://react-native-async-storage.github.io/async-storage/docs/usage/

2024-10-04 06:36 UTC, sjsjsj1246 approved these changes
확인했습니다 고생하셨습니다~

2024-10-04 06:37 UTC, merged